name: My First Pipeline

# This tells the robot WHEN to wake up
on: [push]

# This tells the robot WHAT to do
jobs:
  say_hello_job:
    # This is the computer GitHub will give us to use
    runs-on: ubuntu-latest

    # These are the exact steps to take
    steps:
      - name: Print a greeting
        run: echo "Hello, Pipeline! You successfully set this up."